title: Nourished
description: > # this means to ignore newlines until next key
  食品廃棄物ゼロを人類の最終目標とし、ユーモラスな活動でそれを助長する。ウェブマガジンで為になる情報を配信する。
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Yucho Ho # add your name
author-img: # add your photo
about-author: 地球人兼プログラマーで、密かに社会の役に立つ計画を立てている。実績はまだない。 # add description
organization: Nourished # add your organization
site-img: nourished.png # add site logo
site-img-small: nourished-small.png # add site logo for small screen
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: nourished-jp # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
sass:
  sass_dir: assets/css

paginate: 11
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "Gemfile", "Gemfile.lock", "README*"]
